/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCalculatorFormValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage.eINSTANCE);
		return result;
	}
	
}
