/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.idea.highlighting;

import de.htwg.zeta.xtext.idea.lang.CalculatorFormLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class CalculatorFormBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public CalculatorFormBaseColorSettingsPage() {
		CalculatorFormLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return CalculatorFormLanguage.INSTANCE.getDisplayName();
	}
}
