/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import de.htwg.zeta.xtext.idea.lang.CalculatorFormLanguage;
import org.jetbrains.annotations.NotNull;

public class CalculatorFormSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
    @NotNull
    protected SyntaxHighlighter createHighlighter() {
        return CalculatorFormLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
    }
}
