/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import de.htwg.zeta.xtext.idea.lang.CalculatorFormLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class CalculatorFormCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public CalculatorFormCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(CalculatorFormLanguage.INSTANCE, psiModificationTracker);
	}

}
