/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CalculatorFormGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Model");
		private final Assignment cFormsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFormsFormParserRuleCall_0 = (RuleCall)cFormsAssignment.eContents().get(0);
		
		//Model:
		//	forms+=Form*;
		@Override public ParserRule getRule() { return rule; }
		
		//forms+=Form*
		public Assignment getFormsAssignment() { return cFormsAssignment; }
		
		//Form
		public RuleCall getFormsFormParserRuleCall_0() { return cFormsFormParserRuleCall_0; }
	}
	public class FormElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Form");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFormKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFormElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFormElementsFormElementParserRuleCall_3_0 = (RuleCall)cFormElementsAssignment_3.eContents().get(0);
		private final Assignment cCalculationsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCalculationsCalculateParserRuleCall_4_0 = (RuleCall)cCalculationsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Form:
		//	'form' name=ID '{' formElements+=FormElement* calculations+=Calculate* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'form' name=ID '{' formElements+=FormElement* calculations+=Calculate* '}'
		public Group getGroup() { return cGroup; }
		
		//'form'
		public Keyword getFormKeyword_0() { return cFormKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//formElements+=FormElement*
		public Assignment getFormElementsAssignment_3() { return cFormElementsAssignment_3; }
		
		//FormElement
		public RuleCall getFormElementsFormElementParserRuleCall_3_0() { return cFormElementsFormElementParserRuleCall_3_0; }
		
		//calculations+=Calculate*
		public Assignment getCalculationsAssignment_4() { return cCalculationsAssignment_4; }
		
		//Calculate
		public RuleCall getCalculationsCalculateParserRuleCall_4_0() { return cCalculationsCalculateParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FormElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FormElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFieldParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGroupParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//FormElement:
		//	Field | Group | Page;
		@Override public ParserRule getRule() { return rule; }
		
		//Field | Group | Page
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Field
		public RuleCall getFieldParserRuleCall_0() { return cFieldParserRuleCall_0; }
		
		//Group
		public RuleCall getGroupParserRuleCall_1() { return cGroupParserRuleCall_1; }
		
		//Page
		public RuleCall getPageParserRuleCall_2() { return cPageParserRuleCall_2; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Field");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFieldInputParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFieldSelectParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFieldChoiceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cButtonParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Field:
		//	FieldInput | FieldSelect | FieldChoice | Button;
		@Override public ParserRule getRule() { return rule; }
		
		//FieldInput | FieldSelect | FieldChoice | Button
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FieldInput
		public RuleCall getFieldInputParserRuleCall_0() { return cFieldInputParserRuleCall_0; }
		
		//FieldSelect
		public RuleCall getFieldSelectParserRuleCall_1() { return cFieldSelectParserRuleCall_1; }
		
		//FieldChoice
		public RuleCall getFieldChoiceParserRuleCall_2() { return cFieldChoiceParserRuleCall_2; }
		
		//Button
		public RuleCall getButtonParserRuleCall_3() { return cButtonParserRuleCall_3; }
	}
	public class FieldInputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FieldInput");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cAutofocusAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cAutofocusAutofocusKeyword_2_0 = (Keyword)cAutofocusAssignment_2.eContents().get(0);
		private final Assignment cDisabledAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cDisabledDisabledKeyword_3_0 = (Keyword)cDisabledAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFormKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFormAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFormSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cFormAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLabelKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLabelAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cLabelAssignment_5_1.eContents().get(0);
		private final Assignment cNotdisplayedAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Keyword cNotdisplayedNotdisplayedKeyword_6_0 = (Keyword)cNotdisplayedAssignment_6.eContents().get(0);
		private final Assignment cReadonlyAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final Keyword cReadonlyReadonlyKeyword_7_0 = (Keyword)cReadonlyAssignment_7.eContents().get(0);
		private final Assignment cRequiredAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final Keyword cRequiredRequiredKeyword_8_0 = (Keyword)cRequiredAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cValueKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cValueAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_9_1_0 = (RuleCall)cValueAssignment_9_1.eContents().get(0);
		
		//FieldInput:
		//	'field' name=ID autofocus?='autofocus'? disabled?='disabled'? ('form' form=STRING)? ('label' label=STRING)?
		//	notdisplayed?='notdisplayed'? readonly?='readonly'? required?='required'? ('value' value=STRING)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'field' name=ID autofocus?='autofocus'? disabled?='disabled'? ('form' form=STRING)? ('label' label=STRING)?
		//notdisplayed?='notdisplayed'? readonly?='readonly'? required?='required'? ('value' value=STRING)?
		public Group getGroup() { return cGroup; }
		
		//'field'
		public Keyword getFieldKeyword_0() { return cFieldKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//autofocus?='autofocus'?
		public Assignment getAutofocusAssignment_2() { return cAutofocusAssignment_2; }
		
		//'autofocus'
		public Keyword getAutofocusAutofocusKeyword_2_0() { return cAutofocusAutofocusKeyword_2_0; }
		
		//disabled?='disabled'?
		public Assignment getDisabledAssignment_3() { return cDisabledAssignment_3; }
		
		//'disabled'
		public Keyword getDisabledDisabledKeyword_3_0() { return cDisabledDisabledKeyword_3_0; }
		
		//('form' form=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'form'
		public Keyword getFormKeyword_4_0() { return cFormKeyword_4_0; }
		
		//form=STRING
		public Assignment getFormAssignment_4_1() { return cFormAssignment_4_1; }
		
		//STRING
		public RuleCall getFormSTRINGTerminalRuleCall_4_1_0() { return cFormSTRINGTerminalRuleCall_4_1_0; }
		
		//('label' label=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'label'
		public Keyword getLabelKeyword_5_0() { return cLabelKeyword_5_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_5_1() { return cLabelAssignment_5_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_5_1_0() { return cLabelSTRINGTerminalRuleCall_5_1_0; }
		
		//notdisplayed?='notdisplayed'?
		public Assignment getNotdisplayedAssignment_6() { return cNotdisplayedAssignment_6; }
		
		//'notdisplayed'
		public Keyword getNotdisplayedNotdisplayedKeyword_6_0() { return cNotdisplayedNotdisplayedKeyword_6_0; }
		
		//readonly?='readonly'?
		public Assignment getReadonlyAssignment_7() { return cReadonlyAssignment_7; }
		
		//'readonly'
		public Keyword getReadonlyReadonlyKeyword_7_0() { return cReadonlyReadonlyKeyword_7_0; }
		
		//required?='required'?
		public Assignment getRequiredAssignment_8() { return cRequiredAssignment_8; }
		
		//'required'
		public Keyword getRequiredRequiredKeyword_8_0() { return cRequiredRequiredKeyword_8_0; }
		
		//('value' value=STRING)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'value'
		public Keyword getValueKeyword_9_0() { return cValueKeyword_9_0; }
		
		//value=STRING
		public Assignment getValueAssignment_9_1() { return cValueAssignment_9_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_9_1_0() { return cValueSTRINGTerminalRuleCall_9_1_0; }
	}
	public class FieldSelectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FieldSelect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDropdownKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cAutofocusAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cAutofocusAutofocusKeyword_2_0 = (Keyword)cAutofocusAssignment_2.eContents().get(0);
		private final Assignment cDisabledAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cDisabledDisabledKeyword_3_0 = (Keyword)cDisabledAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFormKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cFormAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cFormSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cFormAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLabelKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLabelAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cLabelAssignment_5_1.eContents().get(0);
		private final Assignment cMultipleAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Keyword cMultipleMultipleKeyword_6_0 = (Keyword)cMultipleAssignment_6.eContents().get(0);
		private final Assignment cRequiredAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final Keyword cRequiredRequiredKeyword_7_0 = (Keyword)cRequiredAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cSizeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cSizeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cSizeINTTerminalRuleCall_8_1_0 = (RuleCall)cSizeAssignment_8_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cChildsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cChildsFieldSelectChildParserRuleCall_10_0 = (RuleCall)cChildsAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//FieldSelect:
		//	'dropdown' name=ID autofocus?='autofocus'? disabled?='disabled'? ('form' form=STRING)? ('label' label=STRING)?
		//	multiple?='multiple'? required?='required'? ('size' size=INT)? '{' childs+=FieldSelectChild* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'dropdown' name=ID autofocus?='autofocus'? disabled?='disabled'? ('form' form=STRING)? ('label' label=STRING)?
		//multiple?='multiple'? required?='required'? ('size' size=INT)? '{' childs+=FieldSelectChild* '}'
		public Group getGroup() { return cGroup; }
		
		//'dropdown'
		public Keyword getDropdownKeyword_0() { return cDropdownKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//autofocus?='autofocus'?
		public Assignment getAutofocusAssignment_2() { return cAutofocusAssignment_2; }
		
		//'autofocus'
		public Keyword getAutofocusAutofocusKeyword_2_0() { return cAutofocusAutofocusKeyword_2_0; }
		
		//disabled?='disabled'?
		public Assignment getDisabledAssignment_3() { return cDisabledAssignment_3; }
		
		//'disabled'
		public Keyword getDisabledDisabledKeyword_3_0() { return cDisabledDisabledKeyword_3_0; }
		
		//('form' form=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'form'
		public Keyword getFormKeyword_4_0() { return cFormKeyword_4_0; }
		
		//form=STRING
		public Assignment getFormAssignment_4_1() { return cFormAssignment_4_1; }
		
		//STRING
		public RuleCall getFormSTRINGTerminalRuleCall_4_1_0() { return cFormSTRINGTerminalRuleCall_4_1_0; }
		
		//('label' label=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'label'
		public Keyword getLabelKeyword_5_0() { return cLabelKeyword_5_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_5_1() { return cLabelAssignment_5_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_5_1_0() { return cLabelSTRINGTerminalRuleCall_5_1_0; }
		
		//multiple?='multiple'?
		public Assignment getMultipleAssignment_6() { return cMultipleAssignment_6; }
		
		//'multiple'
		public Keyword getMultipleMultipleKeyword_6_0() { return cMultipleMultipleKeyword_6_0; }
		
		//required?='required'?
		public Assignment getRequiredAssignment_7() { return cRequiredAssignment_7; }
		
		//'required'
		public Keyword getRequiredRequiredKeyword_7_0() { return cRequiredRequiredKeyword_7_0; }
		
		//('size' size=INT)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'size'
		public Keyword getSizeKeyword_8_0() { return cSizeKeyword_8_0; }
		
		//size=INT
		public Assignment getSizeAssignment_8_1() { return cSizeAssignment_8_1; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_8_1_0() { return cSizeINTTerminalRuleCall_8_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//childs+=FieldSelectChild*
		public Assignment getChildsAssignment_10() { return cChildsAssignment_10; }
		
		//FieldSelectChild
		public RuleCall getChildsFieldSelectChildParserRuleCall_10_0() { return cChildsFieldSelectChildParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class FieldSelectChildElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FieldSelectChild");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFieldOptionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFieldOptionGroupParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//FieldSelectChild:
		//	FieldOption | FieldOptionGroup;
		@Override public ParserRule getRule() { return rule; }
		
		//FieldOption | FieldOptionGroup
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FieldOption
		public RuleCall getFieldOptionParserRuleCall_0() { return cFieldOptionParserRuleCall_0; }
		
		//FieldOptionGroup
		public RuleCall getFieldOptionGroupParserRuleCall_1() { return cFieldOptionGroupParserRuleCall_1; }
	}
	public class FieldOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FieldOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		private final Assignment cDisabledAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cDisabledDisabledKeyword_2_0 = (Keyword)cDisabledAssignment_2.eContents().get(0);
		private final Assignment cSelectedAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cSelectedSelectedKeyword_3_0 = (Keyword)cSelectedAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cTextAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		
		//FieldOption:
		//	'option' text=STRING disabled?='disabled'? selected?='selected'? ('text' text=STRING)? ('value' value=STRING)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'option' text=STRING disabled?='disabled'? selected?='selected'? ('text' text=STRING)? ('value' value=STRING)?
		public Group getGroup() { return cGroup; }
		
		//'option'
		public Keyword getOptionKeyword_0() { return cOptionKeyword_0; }
		
		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }
		
		//disabled?='disabled'?
		public Assignment getDisabledAssignment_2() { return cDisabledAssignment_2; }
		
		//'disabled'
		public Keyword getDisabledDisabledKeyword_2_0() { return cDisabledDisabledKeyword_2_0; }
		
		//selected?='selected'?
		public Assignment getSelectedAssignment_3() { return cSelectedAssignment_3; }
		
		//'selected'
		public Keyword getSelectedSelectedKeyword_3_0() { return cSelectedSelectedKeyword_3_0; }
		
		//('text' text=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'text'
		public Keyword getTextKeyword_4_0() { return cTextKeyword_4_0; }
		
		//text=STRING
		public Assignment getTextAssignment_4_1() { return cTextAssignment_4_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_4_1_0() { return cTextSTRINGTerminalRuleCall_4_1_0; }
		
		//('value' value=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'value'
		public Keyword getValueKeyword_5_0() { return cValueKeyword_5_0; }
		
		//value=STRING
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_5_1_0() { return cValueSTRINGTerminalRuleCall_5_1_0; }
	}
	public class FieldOptionGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FieldOptionGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDisabledAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cDisabledDisabledKeyword_1_0 = (Keyword)cDisabledAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLabelKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLabelAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cLabelAssignment_2_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cOptionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOptionsFieldOptionParserRuleCall_4_0 = (RuleCall)cOptionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FieldOptionGroup:
		//	'option-group' disabled?='disabled'? ('label' label=STRING)? '{' options+=FieldOption* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'option-group' disabled?='disabled'? ('label' label=STRING)? '{' options+=FieldOption* '}'
		public Group getGroup() { return cGroup; }
		
		//'option-group'
		public Keyword getOptionGroupKeyword_0() { return cOptionGroupKeyword_0; }
		
		//disabled?='disabled'?
		public Assignment getDisabledAssignment_1() { return cDisabledAssignment_1; }
		
		//'disabled'
		public Keyword getDisabledDisabledKeyword_1_0() { return cDisabledDisabledKeyword_1_0; }
		
		//('label' label=STRING)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'label'
		public Keyword getLabelKeyword_2_0() { return cLabelKeyword_2_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_2_1() { return cLabelAssignment_2_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_1_0() { return cLabelSTRINGTerminalRuleCall_2_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//options+=FieldOption*
		public Assignment getOptionsAssignment_4() { return cOptionsAssignment_4; }
		
		//FieldOption
		public RuleCall getOptionsFieldOptionParserRuleCall_4_0() { return cOptionsFieldOptionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FieldChoiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FieldChoice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cAutofocusAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cAutofocusAutofocusKeyword_2_0 = (Keyword)cAutofocusAssignment_2.eContents().get(0);
		private final Assignment cCheckedAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cCheckedCheckedKeyword_3_0 = (Keyword)cCheckedAssignment_3.eContents().get(0);
		private final Assignment cDisabledAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cDisabledDisabledKeyword_4_0 = (Keyword)cDisabledAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cFormKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cFormAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cFormSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cFormAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cLabelKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cLabelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cLabelAssignment_6_1.eContents().get(0);
		private final Assignment cMultipleAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final Keyword cMultipleMultipleKeyword_7_0 = (Keyword)cMultipleAssignment_7.eContents().get(0);
		private final Assignment cNotdisplayedAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final Keyword cNotdisplayedNotdisplayedKeyword_8_0 = (Keyword)cNotdisplayedAssignment_8.eContents().get(0);
		private final Assignment cReadonlyAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final Keyword cReadonlyReadonlyKeyword_9_0 = (Keyword)cReadonlyAssignment_9.eContents().get(0);
		private final Assignment cRequiredAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final Keyword cRequiredRequiredKeyword_10_0 = (Keyword)cRequiredAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cValueKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cValueAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_11_1_0 = (RuleCall)cValueAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cOptionsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cOptionsFieldChoiceOptionParserRuleCall_12_1_0 = (RuleCall)cOptionsAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_2 = (Keyword)cGroup_12.eContents().get(2);
		
		//FieldChoice:
		//	'choice' name=ID autofocus?='autofocus'? checked?='checked'? disabled?='disabled'? ('form' form=STRING)? ('label'
		//	label=STRING)? multiple?='multiple'? notdisplayed?='notdisplayed'? readonly?='readonly'? required?='required'?
		//	('value' value=STRING)? ('{' options+=FieldChoiceOption* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'choice' name=ID autofocus?='autofocus'? checked?='checked'? disabled?='disabled'? ('form' form=STRING)? ('label'
		//label=STRING)? multiple?='multiple'? notdisplayed?='notdisplayed'? readonly?='readonly'? required?='required'? ('value'
		//value=STRING)? ('{' options+=FieldChoiceOption* '}')?
		public Group getGroup() { return cGroup; }
		
		//'choice'
		public Keyword getChoiceKeyword_0() { return cChoiceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//autofocus?='autofocus'?
		public Assignment getAutofocusAssignment_2() { return cAutofocusAssignment_2; }
		
		//'autofocus'
		public Keyword getAutofocusAutofocusKeyword_2_0() { return cAutofocusAutofocusKeyword_2_0; }
		
		//checked?='checked'?
		public Assignment getCheckedAssignment_3() { return cCheckedAssignment_3; }
		
		//'checked'
		public Keyword getCheckedCheckedKeyword_3_0() { return cCheckedCheckedKeyword_3_0; }
		
		//disabled?='disabled'?
		public Assignment getDisabledAssignment_4() { return cDisabledAssignment_4; }
		
		//'disabled'
		public Keyword getDisabledDisabledKeyword_4_0() { return cDisabledDisabledKeyword_4_0; }
		
		//('form' form=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'form'
		public Keyword getFormKeyword_5_0() { return cFormKeyword_5_0; }
		
		//form=STRING
		public Assignment getFormAssignment_5_1() { return cFormAssignment_5_1; }
		
		//STRING
		public RuleCall getFormSTRINGTerminalRuleCall_5_1_0() { return cFormSTRINGTerminalRuleCall_5_1_0; }
		
		//('label' label=STRING)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'label'
		public Keyword getLabelKeyword_6_0() { return cLabelKeyword_6_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_6_1() { return cLabelAssignment_6_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_6_1_0() { return cLabelSTRINGTerminalRuleCall_6_1_0; }
		
		//multiple?='multiple'?
		public Assignment getMultipleAssignment_7() { return cMultipleAssignment_7; }
		
		//'multiple'
		public Keyword getMultipleMultipleKeyword_7_0() { return cMultipleMultipleKeyword_7_0; }
		
		//notdisplayed?='notdisplayed'?
		public Assignment getNotdisplayedAssignment_8() { return cNotdisplayedAssignment_8; }
		
		//'notdisplayed'
		public Keyword getNotdisplayedNotdisplayedKeyword_8_0() { return cNotdisplayedNotdisplayedKeyword_8_0; }
		
		//readonly?='readonly'?
		public Assignment getReadonlyAssignment_9() { return cReadonlyAssignment_9; }
		
		//'readonly'
		public Keyword getReadonlyReadonlyKeyword_9_0() { return cReadonlyReadonlyKeyword_9_0; }
		
		//required?='required'?
		public Assignment getRequiredAssignment_10() { return cRequiredAssignment_10; }
		
		//'required'
		public Keyword getRequiredRequiredKeyword_10_0() { return cRequiredRequiredKeyword_10_0; }
		
		//('value' value=STRING)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'value'
		public Keyword getValueKeyword_11_0() { return cValueKeyword_11_0; }
		
		//value=STRING
		public Assignment getValueAssignment_11_1() { return cValueAssignment_11_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_11_1_0() { return cValueSTRINGTerminalRuleCall_11_1_0; }
		
		//('{' options+=FieldChoiceOption* '}')?
		public Group getGroup_12() { return cGroup_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12_0() { return cLeftCurlyBracketKeyword_12_0; }
		
		//options+=FieldChoiceOption*
		public Assignment getOptionsAssignment_12_1() { return cOptionsAssignment_12_1; }
		
		//FieldChoiceOption
		public RuleCall getOptionsFieldChoiceOptionParserRuleCall_12_1_0() { return cOptionsFieldChoiceOptionParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12_2() { return cRightCurlyBracketKeyword_12_2; }
	}
	public class FieldChoiceOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FieldChoiceOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLabelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_1_0 = (RuleCall)cLabelAssignment_1.eContents().get(0);
		private final Assignment cAutofocusAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cAutofocusAutofocusKeyword_2_0 = (Keyword)cAutofocusAssignment_2.eContents().get(0);
		private final Assignment cCheckedAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cCheckedCheckedKeyword_3_0 = (Keyword)cCheckedAssignment_3.eContents().get(0);
		private final Assignment cDisabledAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cDisabledDisabledKeyword_4_0 = (Keyword)cDisabledAssignment_4.eContents().get(0);
		private final Assignment cReadonlyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cReadonlyReadonlyKeyword_5_0 = (Keyword)cReadonlyAssignment_5.eContents().get(0);
		private final Assignment cRequiredAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final Keyword cRequiredRequiredKeyword_6_0 = (Keyword)cRequiredAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cValueKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cValueAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cValueAssignment_7_1.eContents().get(0);
		
		//FieldChoiceOption:
		//	'option' label=STRING autofocus?='autofocus'? checked?='checked'? disabled?='disabled'? readonly?='readonly'?
		//	required?='required'? ('value' value=STRING)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'option' label=STRING autofocus?='autofocus'? checked?='checked'? disabled?='disabled'? readonly?='readonly'?
		//required?='required'? ('value' value=STRING)?
		public Group getGroup() { return cGroup; }
		
		//'option'
		public Keyword getOptionKeyword_0() { return cOptionKeyword_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_1() { return cLabelAssignment_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_1_0() { return cLabelSTRINGTerminalRuleCall_1_0; }
		
		//autofocus?='autofocus'?
		public Assignment getAutofocusAssignment_2() { return cAutofocusAssignment_2; }
		
		//'autofocus'
		public Keyword getAutofocusAutofocusKeyword_2_0() { return cAutofocusAutofocusKeyword_2_0; }
		
		//checked?='checked'?
		public Assignment getCheckedAssignment_3() { return cCheckedAssignment_3; }
		
		//'checked'
		public Keyword getCheckedCheckedKeyword_3_0() { return cCheckedCheckedKeyword_3_0; }
		
		//disabled?='disabled'?
		public Assignment getDisabledAssignment_4() { return cDisabledAssignment_4; }
		
		//'disabled'
		public Keyword getDisabledDisabledKeyword_4_0() { return cDisabledDisabledKeyword_4_0; }
		
		//readonly?='readonly'?
		public Assignment getReadonlyAssignment_5() { return cReadonlyAssignment_5; }
		
		//'readonly'
		public Keyword getReadonlyReadonlyKeyword_5_0() { return cReadonlyReadonlyKeyword_5_0; }
		
		//required?='required'?
		public Assignment getRequiredAssignment_6() { return cRequiredAssignment_6; }
		
		//'required'
		public Keyword getRequiredRequiredKeyword_6_0() { return cRequiredRequiredKeyword_6_0; }
		
		//('value' value=STRING)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'value'
		public Keyword getValueKeyword_7_0() { return cValueKeyword_7_0; }
		
		//value=STRING
		public Assignment getValueAssignment_7_1() { return cValueAssignment_7_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_7_1_0() { return cValueSTRINGTerminalRuleCall_7_1_0; }
	}
	public class GroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLabelKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLabelAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cLabelAssignment_2_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFieldsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFieldsFieldParserRuleCall_4_0 = (RuleCall)cFieldsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Group:
		//	'group' name=ID ('label' label=STRING)? '{' fields+=Field* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'group' name=ID ('label' label=STRING)? '{' fields+=Field* '}'
		public Group getGroup() { return cGroup; }
		
		//'group'
		public Keyword getGroupKeyword_0() { return cGroupKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('label' label=STRING)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'label'
		public Keyword getLabelKeyword_2_0() { return cLabelKeyword_2_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_2_1() { return cLabelAssignment_2_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_1_0() { return cLabelSTRINGTerminalRuleCall_2_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//fields+=Field*
		public Assignment getFieldsAssignment_4() { return cFieldsAssignment_4; }
		
		//Field
		public RuleCall getFieldsFieldParserRuleCall_4_0() { return cFieldsFieldParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cChildsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cChildsPageChildParserRuleCall_2_0 = (RuleCall)cChildsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Page:
		//	'page' '{' childs+=PageChild* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'page' '{' childs+=PageChild* '}'
		public Group getGroup() { return cGroup; }
		
		//'page'
		public Keyword getPageKeyword_0() { return cPageKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//childs+=PageChild*
		public Assignment getChildsAssignment_2() { return cChildsAssignment_2; }
		
		//PageChild
		public RuleCall getChildsPageChildParserRuleCall_2_0() { return cChildsPageChildParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class PageChildElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.PageChild");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGroupParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFieldParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//PageChild:
		//	Group | Field;
		@Override public ParserRule getRule() { return rule; }
		
		//Group | Field
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Group
		public RuleCall getGroupParserRuleCall_0() { return cGroupParserRuleCall_0; }
		
		//Field
		public RuleCall getFieldParserRuleCall_1() { return cFieldParserRuleCall_1; }
	}
	public class ButtonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Button");
		private final RuleCall cButtonSubmitParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Button:
		//	ButtonSubmit;
		@Override public ParserRule getRule() { return rule; }
		
		//ButtonSubmit
		public RuleCall getButtonSubmitParserRuleCall() { return cButtonSubmitParserRuleCall; }
	}
	public class ButtonSubmitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.ButtonSubmit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubmitButtonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cTextAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextAssignment_2.eContents().get(0);
		private final Assignment cAutofocusAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cAutofocusAutofocusKeyword_3_0 = (Keyword)cAutofocusAssignment_3.eContents().get(0);
		private final Assignment cDisabledAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cDisabledDisabledKeyword_4_0 = (Keyword)cDisabledAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		
		//ButtonSubmit:
		//	'submit-button' name=ID text=STRING autofocus?='autofocus'? disabled?='disabled'? ('value' value=STRING)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'submit-button' name=ID text=STRING autofocus?='autofocus'? disabled?='disabled'? ('value' value=STRING)?
		public Group getGroup() { return cGroup; }
		
		//'submit-button'
		public Keyword getSubmitButtonKeyword_0() { return cSubmitButtonKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//text=STRING
		public Assignment getTextAssignment_2() { return cTextAssignment_2; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_2_0() { return cTextSTRINGTerminalRuleCall_2_0; }
		
		//autofocus?='autofocus'?
		public Assignment getAutofocusAssignment_3() { return cAutofocusAssignment_3; }
		
		//'autofocus'
		public Keyword getAutofocusAutofocusKeyword_3_0() { return cAutofocusAutofocusKeyword_3_0; }
		
		//disabled?='disabled'?
		public Assignment getDisabledAssignment_4() { return cDisabledAssignment_4; }
		
		//'disabled'
		public Keyword getDisabledDisabledKeyword_4_0() { return cDisabledDisabledKeyword_4_0; }
		
		//('value' value=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'value'
		public Keyword getValueKeyword_5_0() { return cValueKeyword_5_0; }
		
		//value=STRING
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_5_1_0() { return cValueSTRINGTerminalRuleCall_5_1_0; }
	}
	public class CalculateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Calculate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCalculateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cResultAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cResultFieldCrossReference_1_0 = (CrossReference)cResultAssignment_1.eContents().get(0);
		private final RuleCall cResultFieldQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cResultFieldCrossReference_1_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		
		//// Expression based on http://xsemantics.sourceforge.net/xsemantics-documentation/Expressions-example.html
		//Calculate:
		//	'calculate' result=[Field|QualifiedName] '=' expression=Expression;
		@Override public ParserRule getRule() { return rule; }
		
		//'calculate' result=[Field|QualifiedName] '=' expression=Expression
		public Group getGroup() { return cGroup; }
		
		//'calculate'
		public Keyword getCalculateKeyword_0() { return cCalculateKeyword_0; }
		
		//result=[Field|QualifiedName]
		public Assignment getResultAssignment_1() { return cResultAssignment_1; }
		
		//[Field|QualifiedName]
		public CrossReference getResultFieldCrossReference_1_0() { return cResultFieldCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getResultFieldQualifiedNameParserRuleCall_1_0_1() { return cResultFieldQualifiedNameParserRuleCall_1_0_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Expression");
		private final RuleCall cAdditionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expression:
		//	Addition;
		@Override public ParserRule getRule() { return rule; }
		
		//Addition
		public RuleCall getAdditionParserRuleCall() { return cAdditionParserRuleCall; }
	}
	public class AdditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Addition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplicationParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cPlusLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cMinusLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightMultiplicationParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Addition Expression:
		//	Multiplication (({Plus.left=current} '+' | {Minus.left=current} '-') right=Multiplication)*
		@Override public ParserRule getRule() { return rule; }
		
		//Multiplication (({Plus.left=current} '+' | {Minus.left=current} '-') right=Multiplication)*
		public Group getGroup() { return cGroup; }
		
		//Multiplication
		public RuleCall getMultiplicationParserRuleCall_0() { return cMultiplicationParserRuleCall_0; }
		
		//(({Plus.left=current} '+' | {Minus.left=current} '-') right=Multiplication)*
		public Group getGroup_1() { return cGroup_1; }
		
		//({Plus.left=current} '+' | {Minus.left=current} '-')
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Plus.left=current} '+'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Plus.left=current}
		public Action getPlusLeftAction_1_0_0_0() { return cPlusLeftAction_1_0_0_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1_0_0_1() { return cPlusSignKeyword_1_0_0_1; }
		
		//{Minus.left=current} '-'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Minus.left=current}
		public Action getMinusLeftAction_1_0_1_0() { return cMinusLeftAction_1_0_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_0_1_1() { return cHyphenMinusKeyword_1_0_1_1; }
		
		//right=Multiplication
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Multiplication
		public RuleCall getRightMultiplicationParserRuleCall_1_1_0() { return cRightMultiplicationParserRuleCall_1_1_0; }
	}
	public class MultiplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Multiplication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrefixedParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cMultiLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cDivLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cSolidusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightPrefixedParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Multiplication Expression:
		//	Prefixed (({Multi.left=current} '*' | {Div.left=current} '/') right=Prefixed)*
		@Override public ParserRule getRule() { return rule; }
		
		//Prefixed (({Multi.left=current} '*' | {Div.left=current} '/') right=Prefixed)*
		public Group getGroup() { return cGroup; }
		
		//Prefixed
		public RuleCall getPrefixedParserRuleCall_0() { return cPrefixedParserRuleCall_0; }
		
		//(({Multi.left=current} '*' | {Div.left=current} '/') right=Prefixed)*
		public Group getGroup_1() { return cGroup_1; }
		
		//({Multi.left=current} '*' | {Div.left=current} '/')
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{Multi.left=current} '*'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{Multi.left=current}
		public Action getMultiLeftAction_1_0_0_0() { return cMultiLeftAction_1_0_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_1_0_0_1() { return cAsteriskKeyword_1_0_0_1; }
		
		//{Div.left=current} '/'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{Div.left=current}
		public Action getDivLeftAction_1_0_1_0() { return cDivLeftAction_1_0_1_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0_1_1() { return cSolidusKeyword_1_0_1_1; }
		
		//right=Prefixed
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Prefixed
		public RuleCall getRightPrefixedParserRuleCall_1_1_0() { return cRightPrefixedParserRuleCall_1_1_0; }
	}
	public class PrefixedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Prefixed");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cBooleanNegationAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cExpressionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cExpressionAtomicParserRuleCall_0_2_0 = (RuleCall)cExpressionAssignment_0_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cArithmeticSignedAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cExpressionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExpressionAtomicParserRuleCall_1_2_0 = (RuleCall)cExpressionAssignment_1_2.eContents().get(0);
		private final RuleCall cAtomicParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Prefixed Expression:
		//	{BooleanNegation} => "!" expression=Atomic | {ArithmeticSigned} => "-" expression=Atomic | Atomic
		@Override public ParserRule getRule() { return rule; }
		
		//{BooleanNegation} => "!" expression=Atomic | {ArithmeticSigned} => "-" expression=Atomic | Atomic
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{BooleanNegation} => "!" expression=Atomic
		public Group getGroup_0() { return cGroup_0; }
		
		//{BooleanNegation}
		public Action getBooleanNegationAction_0_0() { return cBooleanNegationAction_0_0; }
		
		//=> "!"
		public Keyword getExclamationMarkKeyword_0_1() { return cExclamationMarkKeyword_0_1; }
		
		//expression=Atomic
		public Assignment getExpressionAssignment_0_2() { return cExpressionAssignment_0_2; }
		
		//Atomic
		public RuleCall getExpressionAtomicParserRuleCall_0_2_0() { return cExpressionAtomicParserRuleCall_0_2_0; }
		
		//{ArithmeticSigned} => "-" expression=Atomic
		public Group getGroup_1() { return cGroup_1; }
		
		//{ArithmeticSigned}
		public Action getArithmeticSignedAction_1_0() { return cArithmeticSignedAction_1_0; }
		
		//=> "-"
		public Keyword getHyphenMinusKeyword_1_1() { return cHyphenMinusKeyword_1_1; }
		
		//expression=Atomic
		public Assignment getExpressionAssignment_1_2() { return cExpressionAssignment_1_2; }
		
		//Atomic
		public RuleCall getExpressionAtomicParserRuleCall_1_2_0() { return cExpressionAtomicParserRuleCall_1_2_0; }
		
		/// * right associativity * / Atomic
		public RuleCall getAtomicParserRuleCall_2() { return cAtomicParserRuleCall_2; }
	}
	public class AtomicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.Atomic");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cNumberLiteralAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cFloatLiteralAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cValueAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cValueFLOATTerminalRuleCall_2_1_0 = (RuleCall)cValueAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cPercentLiteralAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValuePERCENTTerminalRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cFieldReferenceAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Assignment cRefAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cRefFieldCrossReference_4_1_0 = (CrossReference)cRefAssignment_4_1.eContents().get(0);
		private final RuleCall cRefFieldQualifiedNameParserRuleCall_4_1_0_1 = (RuleCall)cRefFieldCrossReference_4_1_0.eContents().get(1);
		
		//Atomic Expression:
		//	'(' Expression ')' | {NumberLiteral} value=INT | {FloatLiteral} value=FLOAT | {PercentLiteral} value=PERCENT |
		//	{FieldReference} ref=[Field|QualifiedName]
		@Override public ParserRule getRule() { return rule; }
		
		//'(' Expression ')' | {NumberLiteral} value=INT | {FloatLiteral} value=FLOAT | {PercentLiteral} value=PERCENT |
		//{FieldReference} ref=[Field|QualifiedName]
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'(' Expression ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//Expression
		public RuleCall getExpressionParserRuleCall_0_1() { return cExpressionParserRuleCall_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//{NumberLiteral} value=INT
		public Group getGroup_1() { return cGroup_1; }
		
		//{NumberLiteral}
		public Action getNumberLiteralAction_1_0() { return cNumberLiteralAction_1_0; }
		
		//value=INT
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_1_1_0() { return cValueINTTerminalRuleCall_1_1_0; }
		
		//{FloatLiteral} value=FLOAT
		public Group getGroup_2() { return cGroup_2; }
		
		//{FloatLiteral}
		public Action getFloatLiteralAction_2_0() { return cFloatLiteralAction_2_0; }
		
		//value=FLOAT
		public Assignment getValueAssignment_2_1() { return cValueAssignment_2_1; }
		
		//FLOAT
		public RuleCall getValueFLOATTerminalRuleCall_2_1_0() { return cValueFLOATTerminalRuleCall_2_1_0; }
		
		//{PercentLiteral} value=PERCENT
		public Group getGroup_3() { return cGroup_3; }
		
		//{PercentLiteral}
		public Action getPercentLiteralAction_3_0() { return cPercentLiteralAction_3_0; }
		
		//value=PERCENT
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//PERCENT
		public RuleCall getValuePERCENTTerminalRuleCall_3_1_0() { return cValuePERCENTTerminalRuleCall_3_1_0; }
		
		//{FieldReference} ref=[Field|QualifiedName]
		public Group getGroup_4() { return cGroup_4; }
		
		//{FieldReference}
		public Action getFieldReferenceAction_4_0() { return cFieldReferenceAction_4_0; }
		
		//ref=[Field|QualifiedName]
		public Assignment getRefAssignment_4_1() { return cRefAssignment_4_1; }
		
		//[Field|QualifiedName]
		public CrossReference getRefFieldCrossReference_4_1_0() { return cRefFieldCrossReference_4_1_0; }
		
		//QualifiedName
		public RuleCall getRefFieldQualifiedNameParserRuleCall_4_1_0_1() { return cRefFieldQualifiedNameParserRuleCall_4_1_0_1; }
	}
	
	
	private final ModelElements pModel;
	private final FormElements pForm;
	private final FormElementElements pFormElement;
	private final FieldElements pField;
	private final FieldInputElements pFieldInput;
	private final FieldSelectElements pFieldSelect;
	private final FieldSelectChildElements pFieldSelectChild;
	private final FieldOptionElements pFieldOption;
	private final FieldOptionGroupElements pFieldOptionGroup;
	private final FieldChoiceElements pFieldChoice;
	private final FieldChoiceOptionElements pFieldChoiceOption;
	private final GroupElements pGroup;
	private final PageElements pPage;
	private final PageChildElements pPageChild;
	private final ButtonElements pButton;
	private final ButtonSubmitElements pButtonSubmit;
	private final CalculateElements pCalculate;
	private final QualifiedNameElements pQualifiedName;
	private final ExpressionElements pExpression;
	private final AdditionElements pAddition;
	private final MultiplicationElements pMultiplication;
	private final PrefixedElements pPrefixed;
	private final AtomicElements pAtomic;
	private final TerminalRule tID;
	private final TerminalRule tINT;
	private final TerminalRule tFLOAT;
	private final TerminalRule tPERCENT;
	private final TerminalRule tSTRING;
	private final TerminalRule tML_COMMENT;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tWS;
	private final TerminalRule tANY_OTHER;
	
	private final Grammar grammar;

	@Inject
	public CalculatorFormGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pModel = new ModelElements();
		this.pForm = new FormElements();
		this.pFormElement = new FormElementElements();
		this.pField = new FieldElements();
		this.pFieldInput = new FieldInputElements();
		this.pFieldSelect = new FieldSelectElements();
		this.pFieldSelectChild = new FieldSelectChildElements();
		this.pFieldOption = new FieldOptionElements();
		this.pFieldOptionGroup = new FieldOptionGroupElements();
		this.pFieldChoice = new FieldChoiceElements();
		this.pFieldChoiceOption = new FieldChoiceOptionElements();
		this.pGroup = new GroupElements();
		this.pPage = new PageElements();
		this.pPageChild = new PageChildElements();
		this.pButton = new ButtonElements();
		this.pButtonSubmit = new ButtonSubmitElements();
		this.pCalculate = new CalculateElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pExpression = new ExpressionElements();
		this.pAddition = new AdditionElements();
		this.pMultiplication = new MultiplicationElements();
		this.pPrefixed = new PrefixedElements();
		this.pAtomic = new AtomicElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.ID");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.INT");
		this.tFLOAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.FLOAT");
		this.tPERCENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.PERCENT");
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.STRING");
		this.tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.ML_COMMENT");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.SL_COMMENT");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.WS");
		this.tANY_OTHER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.htwg.zeta.xtext.CalculatorForm.ANY_OTHER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.htwg.zeta.xtext.CalculatorForm".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Model:
	//	forms+=Form*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Form:
	//	'form' name=ID '{' formElements+=FormElement* calculations+=Calculate* '}';
	public FormElements getFormAccess() {
		return pForm;
	}
	
	public ParserRule getFormRule() {
		return getFormAccess().getRule();
	}
	
	//FormElement:
	//	Field | Group | Page;
	public FormElementElements getFormElementAccess() {
		return pFormElement;
	}
	
	public ParserRule getFormElementRule() {
		return getFormElementAccess().getRule();
	}
	
	//Field:
	//	FieldInput | FieldSelect | FieldChoice | Button;
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//FieldInput:
	//	'field' name=ID autofocus?='autofocus'? disabled?='disabled'? ('form' form=STRING)? ('label' label=STRING)?
	//	notdisplayed?='notdisplayed'? readonly?='readonly'? required?='required'? ('value' value=STRING)?;
	public FieldInputElements getFieldInputAccess() {
		return pFieldInput;
	}
	
	public ParserRule getFieldInputRule() {
		return getFieldInputAccess().getRule();
	}
	
	//FieldSelect:
	//	'dropdown' name=ID autofocus?='autofocus'? disabled?='disabled'? ('form' form=STRING)? ('label' label=STRING)?
	//	multiple?='multiple'? required?='required'? ('size' size=INT)? '{' childs+=FieldSelectChild* '}';
	public FieldSelectElements getFieldSelectAccess() {
		return pFieldSelect;
	}
	
	public ParserRule getFieldSelectRule() {
		return getFieldSelectAccess().getRule();
	}
	
	//FieldSelectChild:
	//	FieldOption | FieldOptionGroup;
	public FieldSelectChildElements getFieldSelectChildAccess() {
		return pFieldSelectChild;
	}
	
	public ParserRule getFieldSelectChildRule() {
		return getFieldSelectChildAccess().getRule();
	}
	
	//FieldOption:
	//	'option' text=STRING disabled?='disabled'? selected?='selected'? ('text' text=STRING)? ('value' value=STRING)?;
	public FieldOptionElements getFieldOptionAccess() {
		return pFieldOption;
	}
	
	public ParserRule getFieldOptionRule() {
		return getFieldOptionAccess().getRule();
	}
	
	//FieldOptionGroup:
	//	'option-group' disabled?='disabled'? ('label' label=STRING)? '{' options+=FieldOption* '}';
	public FieldOptionGroupElements getFieldOptionGroupAccess() {
		return pFieldOptionGroup;
	}
	
	public ParserRule getFieldOptionGroupRule() {
		return getFieldOptionGroupAccess().getRule();
	}
	
	//FieldChoice:
	//	'choice' name=ID autofocus?='autofocus'? checked?='checked'? disabled?='disabled'? ('form' form=STRING)? ('label'
	//	label=STRING)? multiple?='multiple'? notdisplayed?='notdisplayed'? readonly?='readonly'? required?='required'?
	//	('value' value=STRING)? ('{' options+=FieldChoiceOption* '}')?;
	public FieldChoiceElements getFieldChoiceAccess() {
		return pFieldChoice;
	}
	
	public ParserRule getFieldChoiceRule() {
		return getFieldChoiceAccess().getRule();
	}
	
	//FieldChoiceOption:
	//	'option' label=STRING autofocus?='autofocus'? checked?='checked'? disabled?='disabled'? readonly?='readonly'?
	//	required?='required'? ('value' value=STRING)?;
	public FieldChoiceOptionElements getFieldChoiceOptionAccess() {
		return pFieldChoiceOption;
	}
	
	public ParserRule getFieldChoiceOptionRule() {
		return getFieldChoiceOptionAccess().getRule();
	}
	
	//Group:
	//	'group' name=ID ('label' label=STRING)? '{' fields+=Field* '}';
	public GroupElements getGroupAccess() {
		return pGroup;
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}
	
	//Page:
	//	'page' '{' childs+=PageChild* '}';
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}
	
	//PageChild:
	//	Group | Field;
	public PageChildElements getPageChildAccess() {
		return pPageChild;
	}
	
	public ParserRule getPageChildRule() {
		return getPageChildAccess().getRule();
	}
	
	//Button:
	//	ButtonSubmit;
	public ButtonElements getButtonAccess() {
		return pButton;
	}
	
	public ParserRule getButtonRule() {
		return getButtonAccess().getRule();
	}
	
	//ButtonSubmit:
	//	'submit-button' name=ID text=STRING autofocus?='autofocus'? disabled?='disabled'? ('value' value=STRING)?;
	public ButtonSubmitElements getButtonSubmitAccess() {
		return pButtonSubmit;
	}
	
	public ParserRule getButtonSubmitRule() {
		return getButtonSubmitAccess().getRule();
	}
	
	//// Expression based on http://xsemantics.sourceforge.net/xsemantics-documentation/Expressions-example.html
	//Calculate:
	//	'calculate' result=[Field|QualifiedName] '=' expression=Expression;
	public CalculateElements getCalculateAccess() {
		return pCalculate;
	}
	
	public ParserRule getCalculateRule() {
		return getCalculateAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//Expression:
	//	Addition;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Addition Expression:
	//	Multiplication (({Plus.left=current} '+' | {Minus.left=current} '-') right=Multiplication)*
	public AdditionElements getAdditionAccess() {
		return pAddition;
	}
	
	public ParserRule getAdditionRule() {
		return getAdditionAccess().getRule();
	}
	
	//Multiplication Expression:
	//	Prefixed (({Multi.left=current} '*' | {Div.left=current} '/') right=Prefixed)*
	public MultiplicationElements getMultiplicationAccess() {
		return pMultiplication;
	}
	
	public ParserRule getMultiplicationRule() {
		return getMultiplicationAccess().getRule();
	}
	
	//Prefixed Expression:
	//	{BooleanNegation} => "!" expression=Atomic | {ArithmeticSigned} => "-" expression=Atomic | Atomic
	public PrefixedElements getPrefixedAccess() {
		return pPrefixed;
	}
	
	public ParserRule getPrefixedRule() {
		return getPrefixedAccess().getRule();
	}
	
	//Atomic Expression:
	//	'(' Expression ')' | {NumberLiteral} value=INT | {FloatLiteral} value=FLOAT | {PercentLiteral} value=PERCENT |
	//	{FieldReference} ref=[Field|QualifiedName]
	public AtomicElements getAtomicAccess() {
		return pAtomic;
	}
	
	public ParserRule getAtomicRule() {
		return getAtomicAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal INT returns ecore::EIntegerObject:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return tINT;
	}
	
	//terminal FLOAT returns ecore::EFloat:
	//	INT '.' INT;
	public TerminalRule getFLOATRule() {
		return tFLOAT;
	}
	
	//terminal PERCENT:
	//	(INT | FLOAT) '%';
	public TerminalRule getPERCENTRule() {
		return tPERCENT;
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return tML_COMMENT;
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return tWS;
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return tANY_OTHER;
	}
}
