/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arithmetic Signed</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getArithmeticSigned()
 * @model
 * @generated
 */
public interface ArithmeticSigned extends UnaryOperation
{
} // ArithmeticSigned
