/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getButton()
 * @model
 * @generated
 */
public interface Button extends Field
{
} // Button
