/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
