/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Choice Option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#getLabel <em>Label</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isAutofocus <em>Autofocus</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isChecked <em>Checked</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isDisabled <em>Disabled</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isReadonly <em>Readonly</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isRequired <em>Required</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption()
 * @model
 * @generated
 */
public interface FieldChoiceOption extends EObject
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Autofocus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Autofocus</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Autofocus</em>' attribute.
   * @see #setAutofocus(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption_Autofocus()
   * @model
   * @generated
   */
  boolean isAutofocus();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isAutofocus <em>Autofocus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Autofocus</em>' attribute.
   * @see #isAutofocus()
   * @generated
   */
  void setAutofocus(boolean value);

  /**
   * Returns the value of the '<em><b>Checked</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Checked</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Checked</em>' attribute.
   * @see #setChecked(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption_Checked()
   * @model
   * @generated
   */
  boolean isChecked();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isChecked <em>Checked</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Checked</em>' attribute.
   * @see #isChecked()
   * @generated
   */
  void setChecked(boolean value);

  /**
   * Returns the value of the '<em><b>Disabled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Disabled</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disabled</em>' attribute.
   * @see #setDisabled(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption_Disabled()
   * @model
   * @generated
   */
  boolean isDisabled();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isDisabled <em>Disabled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disabled</em>' attribute.
   * @see #isDisabled()
   * @generated
   */
  void setDisabled(boolean value);

  /**
   * Returns the value of the '<em><b>Readonly</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Readonly</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Readonly</em>' attribute.
   * @see #setReadonly(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption_Readonly()
   * @model
   * @generated
   */
  boolean isReadonly();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isReadonly <em>Readonly</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Readonly</em>' attribute.
   * @see #isReadonly()
   * @generated
   */
  void setReadonly(boolean value);

  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Required</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute.
   * @see #setRequired(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption_Required()
   * @model
   * @generated
   */
  boolean isRequired();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#isRequired <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required</em>' attribute.
   * @see #isRequired()
   * @generated
   */
  void setRequired(boolean value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldChoiceOption_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldChoiceOption#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // FieldChoiceOption
