/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getName <em>Name</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isAutofocus <em>Autofocus</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isDisabled <em>Disabled</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getForm <em>Form</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getLabel <em>Label</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isMultiple <em>Multiple</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isRequired <em>Required</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getSize <em>Size</em>}</li>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getChilds <em>Childs</em>}</li>
 * </ul>
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect()
 * @model
 * @generated
 */
public interface FieldSelect extends Field
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Autofocus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Autofocus</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Autofocus</em>' attribute.
   * @see #setAutofocus(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Autofocus()
   * @model
   * @generated
   */
  boolean isAutofocus();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isAutofocus <em>Autofocus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Autofocus</em>' attribute.
   * @see #isAutofocus()
   * @generated
   */
  void setAutofocus(boolean value);

  /**
   * Returns the value of the '<em><b>Disabled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Disabled</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disabled</em>' attribute.
   * @see #setDisabled(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Disabled()
   * @model
   * @generated
   */
  boolean isDisabled();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isDisabled <em>Disabled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disabled</em>' attribute.
   * @see #isDisabled()
   * @generated
   */
  void setDisabled(boolean value);

  /**
   * Returns the value of the '<em><b>Form</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Form</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Form</em>' attribute.
   * @see #setForm(String)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Form()
   * @model
   * @generated
   */
  String getForm();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getForm <em>Form</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Form</em>' attribute.
   * @see #getForm()
   * @generated
   */
  void setForm(String value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Multiple</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multiple</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiple</em>' attribute.
   * @see #setMultiple(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Multiple()
   * @model
   * @generated
   */
  boolean isMultiple();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isMultiple <em>Multiple</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiple</em>' attribute.
   * @see #isMultiple()
   * @generated
   */
  void setMultiple(boolean value);

  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Required</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute.
   * @see #setRequired(boolean)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Required()
   * @model
   * @generated
   */
  boolean isRequired();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#isRequired <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required</em>' attribute.
   * @see #isRequired()
   * @generated
   */
  void setRequired(boolean value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(Integer)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Size()
   * @model
   * @generated
   */
  Integer getSize();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.FieldSelect#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(Integer value);

  /**
   * Returns the value of the '<em><b>Childs</b></em>' containment reference list.
   * The list contents are of type {@link de.htwg.zeta.xtext.calculatorForm.FieldSelectChild}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Childs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Childs</em>' containment reference list.
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getFieldSelect_Childs()
   * @model containment="true"
   * @generated
   */
  EList<FieldSelectChild> getChilds();

} // FieldSelect
