/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getField()
 * @model
 * @generated
 */
public interface Field extends FormElement, PageChild, ExpressionVariable
{
} // Field
