/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getInputVariable()
 * @model
 * @generated
 */
public interface InputVariable extends EObject
{
} // InputVariable
