/**
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.calculatorForm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwg.zeta.xtext.calculatorForm.ReferenceLiteral#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getReferenceLiteral()
 * @model
 * @generated
 */
public interface ReferenceLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(ExpressionVariable)
   * @see de.htwg.zeta.xtext.calculatorForm.CalculatorFormPackage#getReferenceLiteral_Ref()
   * @model
   * @generated
   */
  ExpressionVariable getRef();

  /**
   * Sets the value of the '{@link de.htwg.zeta.xtext.calculatorForm.ReferenceLiteral#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(ExpressionVariable value);

} // ReferenceLiteral
