/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.parser.antlr;

import com.google.inject.Inject;
import de.htwg.zeta.xtext.parser.antlr.internal.InternalCalculatorFormParser;
import de.htwg.zeta.xtext.services.CalculatorFormGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CalculatorFormParser extends AbstractAntlrParser {

	@Inject
	private CalculatorFormGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCalculatorFormParser createParser(XtextTokenStream stream) {
		return new InternalCalculatorFormParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CalculatorFormGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CalculatorFormGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
