/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractCalculatorFormFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "cform";

	protected AbstractCalculatorFormFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "CalculatorForm files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "CalculatorForm";
	}

}
