/*
 * generated by Xtext 2.9.2
 */
package de.htwg.zeta.xtext.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class CalculatorFormLanguage extends AbstractXtextLanguage {

	public static final CalculatorFormLanguage INSTANCE = new CalculatorFormLanguage();

	private CalculatorFormLanguage() {
		super("de.htwg.zeta.xtext.CalculatorForm");
	}

}
